<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>Ana Acuña | Assignment 3: Information Architecture</title>
		<link rel="stylesheet" href="css/styles.css">
	</head>

	<body>

	<div class="container">
		<div id="left"></div>
		<div id="right"></div>
		<div id="top"></div>
		<div id="bottom"></div>

		<header>
			<h1>Ana Acuña</h1>
			<img src="images/ana-acuna.jpg" alt="Ana Acuña">
		</header>

		<aside>
			<ul>
				<li>Marketing student flirting with Computer Science</li>
				<li>Cat lover</li>
				<li>Looking for the perfect first tattoo</li>
			</ul>
		</aside>

	</div>