<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>Andrew Thankson | Assignment 3: Information Architecture</title>
		<link rel="stylesheet" href="css/styles.css">
	</head>

	<body>

	<div class="container">
		<div id="left"></div>
		<div id="right"></div>
		<div id="top"></div>
		<div id="bottom"></div>

		<header>
			<h1>Andrew Thankson</h1>
			<img src="images/andrew-thankson.jpg" alt="Andrew Thankson">
		</header>

		<aside class="aside_a">
			<ul>
				<li>Computer Science Student, University of Rochester</li>
				<li>Freelance Web Developer</li>
				<li>Entrepreneur</li>
			</ul>
		</aside>

	</div>