<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>Dominique Dorvil | Assignment 3: Information Architecture</title>
		<link rel="stylesheet" href="css/styles.css">
	</head>

	<body>

	<div class="container">
		<div id="left"></div>
		<div id="right"></div>
		<div id="top"></div>
		<div id="bottom"></div>

		<header>
			<h1>Dominique Dorvil</h1>
			<img src="images/dominique-dorvil.jpg" alt="Dominique Dorvil">
		</header>

		<aside class="aside_d">
			<ul>
				<li>Artist</li>
				<li>Writer</li>
				<li>CS and Digital Media Studies Major</li>
			</ul>
		</aside>

	</div>