<nav>
	<ul>
		<!--<li><a href="index.php" class="menu"> Home</a></li>-->
		<li><div class="wrapper">
			<a href="index.php" class="menu"><img src="images/home.png" alt="Home" class="hover"><p class="text">Home</p></a>
		</div></li>

		<li><div class="wrapper">
			<a href="ana-acuna.php"><img src="images/a_logo.png" alt="Ana Acuña" class="hover"><p class="text">Ana Acuña</p></a>
		</div></li>

		<li><div class="wrapper">
			<a href="andrew-thankson.php"><img src="images/an_logo.png" alt="Andrew Thankson" class="hover"><p class="text">Andrew Thankson</p></a>
		</div></li>

		<li><div class="wrapper">
			<a href="dominique-dorvil.php"><img src="images/d_logo.png" alt="Dominique Dorvil" class="hover"><p class="text">Dominique Dorvil</p></a>
		</div></li>
	</ul>
</nav>